### ISSUE TITLE
FR: Multidoc record

### ISSUE THREAD

**Issue by wlynch** [eddiezane/hook#5]
Many webhook providers will send all events to a single endpoint. We should make it easy to record multiple events to the same file.

When running hook in record mode, additional events that are received should be appended to the file as a separate document, separated with `---`

e.g.

```yaml
method: POST
body: foo
---
method: GET
body: bar
```
