### ISSUE TITLE
FR: URL Parameters

### ISSUE THREAD

**Issue by wlynch** [eddiezane/hook#6]
Similar to headers, webhooks may contain URL parameters that we will need to record.

Example: http://localhost:8080/hook?foo=bar

```yaml
method: GET
params:
  foo: bar
```
